# -*- coding: utf-8 -*-
"""
Generates doping-ontology-analytes.ttl

Metabolites named in the case corpus. A metabolite is not an entry of the
Prohibited List, so it receives no prohibition applicability. Each link to the
substance it derives from is asserted only where a decision in the corpus
states the relation, and that decision is cited on the assertion.

A metabolite may have more than one parent where the deciding body records
that the parent cannot be determined. The relation is asserted to each parent
the decision names, and the decision's own statement is quoted.
"""
import sys

# (local name, label, [parent substance local names], source decision, wording)
METABOLITES = [
 ("Benzoylecgonine", "Benzoylecgonine", ["Substance_Cocaine"], "CAS 2006/A/1130",
  "Benzoylecgonine and Methylecgonine, which are metabolites of cocaine"),
 ("Methylecgonine", "Methylecgonine", ["Substance_Cocaine"], "CAS 2006/A/1130",
  "Benzoylecgonine and Methylecgonine, which are metabolites of cocaine"),
 ("CarboxyTHC", "Carboxy-THC", ["Substance_Tetrahydrocannabinols"], "CAS 2008/A/1577",
  "Carboxy-THC (THCA), a metabolite of marijuana"),
 ("Norandrosterone_19", "19-Norandrosterone", ["Substance_Nandrolone"], "CAS 2010/A/2311",
  "Norandrosterone is a metabolite of nandrolone or its precursors"),
 ("Noretiocholanolone_19", "19-Noretiocholanolone", ["Substance_Nandrolone"], "CAS 2017/A/5175",
  "19-norandrosterone and 19-noretiocholanolone, which are metabolites of nandrolone"),
 # named in national first instance decisions
 ("Metandienone_LTM", "17β-hydroxymethyl,17α-methyl-18-norandrost-1,4,13-trien-3-one",
  ["Substance_Metandienone"], "National Anti-Doping Panel (United Kingdom) SR/007/2023",
  "a Metabolite of the Prohibited Substance metandienone, namely "
  "17β-hydroxymethyl,17α-methyl-18-norandrost-1,4,13-trien-3-one"),
 ("Oxymetholone_Methasterone_LTM",
  "18-nor-17β-hydroxymethyl-17α-methyl-2α-methyl-5α-androst-13-en-3-one",
  ["Substance_Oxymetholone", "Substance_Methasterone"],
  "National Anti-Doping Panel (United Kingdom) SR/056/2022",
  "either oxymetholone or methasterone could be a parent substance of the Metabolite; "
  "it is not scientifically possible to specify which of the two was in fact the relevant parent"),
 ("Oxandrolone_LTM",
  "17a-hydroxymethyl-17β-methyl-18-nor-2-oxa-5a-androst-13-en-3-one",
  ["Substance_Oxandrolone"], "Agence française de lutte contre le dopage D. 2025-01",
  "17a-hydroxymethyl-17β-methyl-18-nor-2-oxa-5a-androst-13-en-3-one, "
  "métabolite long terme de l'oxandrolone"),
]

# further display names by which a decision may refer to a metabolite
ALT_LABELS = {
 "Norandrosterone_19": ["Norandrosterone"],
}

HEAD = """@prefix adro: <https://w3id.org/adro/> .
@prefix obo:  <http://purl.obolibrary.org/obo/> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dcterms: <http://purl.org/dc/terms/> .

<https://w3id.org/adro/analytes> a owl:Ontology ;
    owl:imports <https://w3id.org/adro/substances> ;
    dcterms:title "Anti-Doping Regulation Ontology: metabolites named in the case corpus"@en ;
    rdfs:comment "Generated by scripts/build_analytes.py. Each metabolite relation is asserted only where a decision in the corpus states it, and that decision is cited. Where a decision records that the parent substance cannot be determined, the relation is asserted to every parent the decision names."@en .

"""

def main(out):
    o, multi = [HEAD], 0
    for name, label, parents, src, wording in METABOLITES:
        alt = "".join(f'    rdfs:label "{a}"@en ;\n' for a in ALT_LABELS.get(name, []))
        rel = " , ".join("adro:" + p for p in parents)
        note = ""
        if len(parents) > 1:
            multi += 1
            note = ('    rdfs:comment "The deciding body recorded that the parent substance '
                    'cannot be determined between those named. Both are asserted; neither is '
                    'asserted to the exclusion of the other."@en ;\n')
        o.append(f"""adro:Substance_{name} a adro:Metabolite ;
    rdfs:label "{label}"@en ;
{alt}    adro:isMetaboliteOf {rel} ;
{note}    obo:IAO_0000119 "{src}" ;
    rdfs:comment "As stated in {src}: {wording}."@en .

""")
    open(out, "w", encoding="utf-8").write("".join(o))
    print("metabolites", len(METABOLITES), "of which with more than one parent", multi)

main(sys.argv[1])
