# -*- coding: utf-8 -*-
"""
Builds the single-file releases from the modules.

The modules are the source. A reviewer who wants one artefact to open, or a
tool that does not follow owl:imports, gets it from here rather than from a
hand-maintained copy.

Produces:
  dist/adro-full.ttl   every module merged, imports resolved and dropped
  dist/adro-full.owl   the same, in RDF/XML
  dist/adro-tbox.ttl   the core alone, for anyone who wants the vocabulary only
  dist/adro-tbox.owl   the same, in RDF/XML

BFO and IAO are not merged in. They are imported by IRI, as an ontology that
reuses them should, and the catalog resolves them to the local copies.
"""
import os, sys, rdflib
from rdflib import RDF, OWL, URIRef, Namespace, Literal, RDFS

ADRO = "https://w3id.org/adro/"
MODULES = ["doping-ontology-core.ttl", "doping-ontology-designations.ttl",
           "doping-ontology-substances.ttl", "doping-ontology-analytes.ttl",
           "doping-ontology-cases-cas.ttl", "doping-ontology-cases-national.ttl",
           "doping-ontology-procedure.ttl"]

def merge(root, files, iri, title, version):
    g = rdflib.Graph()
    for f in files:
        g.parse(os.path.join(root, f), format="turtle")
    # drop every module header; the merged file carries one of its own
    for s in list(g.subjects(RDF.type, OWL.Ontology)):
        for t in list(g.triples((s, None, None))):
            g.remove(t)
    o = URIRef(iri)
    g.add((o, RDF.type, OWL.Ontology))
    g.add((o, OWL.versionIRI, URIRef(iri + "/" + version)))
    g.add((o, OWL.imports, URIRef("http://purl.obolibrary.org/obo/bfo.owl")))
    g.add((o, OWL.imports, URIRef("http://purl.obolibrary.org/obo/iao.owl")))
    g.add((o, URIRef("http://purl.org/dc/terms/title"), Literal(title, lang="en")))
    g.add((o, RDFS.comment, Literal(
        "Built by scripts/build_release.py from the modules, which are the source. "
        "Do not edit this file: edit the module and build again. The Basic Formal "
        "Ontology and the Information Artifact Ontology are imported by IRI rather "
        "than merged in; the OASIS catalog in this directory resolves them, and every "
        "module, to local copies.", lang="en")))
    g.bind("adro", Namespace(ADRO))
    g.bind("obo", Namespace("http://purl.obolibrary.org/obo/"))
    g.bind("dcterms", Namespace("http://purl.org/dc/terms/"))
    return g

def main(root, version):
    out = os.path.join(root, "dist")
    os.makedirs(out, exist_ok=True)
    full = merge(root, MODULES, ADRO + "full",
                 "Anti-Doping Regulation Ontology, complete", version)
    tbox = merge(root, MODULES[:1], ADRO + "tbox",
                 "Anti-Doping Regulation Ontology, vocabulary only", version)
    for g, name in ((full, "adro-full"), (tbox, "adro-tbox")):
        for fmt, ext in (("turtle", "ttl"), ("xml", "owl")):
            p = os.path.join(out, f"{name}.{ext}")
            g.serialize(p, format=fmt)
            print(f"{p}  {len(g)} triples  {os.path.getsize(p)//1024} KB")

main(sys.argv[1] if len(sys.argv) > 1 else ".",
     sys.argv[2] if len(sys.argv) > 2 else "2026-09-12")
